#import selenium
#from selenium import webdriver
#import time
#import pandas as pd
#from selenium.webdriver.chrome.service import Service
#from selenium.webdriver.common.action_chains import ActionChains
#from webdriver_manager.chrome import ChromeDriverManager
#service = Service(ChromeDriverManager().install())
#chrome_options = webdriver.ChromeOptions()
#driver = webdriver.Chrome(service=service, options=chrome_options)

In [ ]:
driver.get('https://www.amazon.com.tr/gp/bestsellers/home/ref=zg_bs_home_sm')

In [ ]:
sheet_list = []
def scrape_data():
    #marka_name_location = ("xpath", "//div/a/span/div")
    sellcount_name_location = ("xpath", "//span[@class='a-size-small']")
    #price_name_location = ("xpath", "//span[contains(@class, '_cDEzb_p13n-sc-price_3mJ9Z')]")
    
    marka_name_button = driver.find_elements(*marka_name_location)
    sellcount_name_button = driver.find_elements(*sellcount_name_location)
    price_name_button = driver.find_elements(*price_name_location)
    
    for marka_name, sellcount_name, price_name in zip(marka_name_button, sellcount_name_button, price_name_button):
        Marka = marka_name.text
        Sellcount = sellcount_name.text
        Price = price_name.text
        sheet_list.append((Marka, Sellcount, Price))


scrape_data()

scroll_pause_time = 2  
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
   
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(scroll_pause_time)

    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

next_button = driver.find_element("xpath", "//a[contains(@href, '/gp/bestsellers/home/ref=zg_bs_pg_2_home')]")
next_button.click()
time.sleep(3)  

scrape_data()

In [ ]:
df = pd.DataFrame(sheet_list)

In [ ]:
df.to_excel('amazon_best_sellers_thisweek.xlsx', index=False)

In [111]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings( action = 'ignore')

In [22]:
dataset = pd.read_csv('amazon_best_sellers_thisweek.csv')

In [24]:
dataset

Products  SellCounts         Price
0    Hawk Gaming Chair FAB V4 Oyuncu Koltuğu       4.107   6.049,00 TL
1   LEGO ICONS Orkide 10311 - Yetişkinler İç      12.368   1.659,01 TL
2   Philips LEDBulb 13-23W/90W E27 6500K Bey     834.000     157,50 TL
3   Philips XW9383/01 Kablosuz Islak-Kuru El     229.000  20.999,00 TL
4   Songmics Yarış Koltuğu, Ofis Koltuğu, Oy       5.228   3.199,99 TL
..                                       ...         ...           ...
72        Karcher SC 2 Deluxe Buharlı Makine     148.000     159,00 TL
73                  4'lü Çekmece Düzenleyici     267.000     389,98 TL
74  Elektrikli motor turbo zemin fırçası baş       1.099   2.740,00 TL
75  Bacak Yastık. Viskoelastik Yastık. Ortop       8.626     460,00 TL
76  Philips Hue GO V2 Taşınabilir Akıllı Led     122.000      69,00 TL

[77 rows x 3 columns]

In [28]:
dataset['Price'] = dataset['Price'].str.replace(' TL', '', regex=False) 
dataset['Price'] = dataset['Price'].str.replace('.', '', regex=False)
dataset['Price'] = dataset['Price'].str.replace(',', '.', regex=False)
dataset['Price'] = dataset['Price'].astype(float)


In [30]:
dataset.dtypes

Products       object
SellCounts    float64
Price         float64
dtype: object

In [32]:
x = dataset

In [34]:
x

Products  SellCounts     Price
0    Hawk Gaming Chair FAB V4 Oyuncu Koltuğu       4.107   6049.00
1   LEGO ICONS Orkide 10311 - Yetişkinler İç      12.368   1659.01
2   Philips LEDBulb 13-23W/90W E27 6500K Bey     834.000    157.50
3   Philips XW9383/01 Kablosuz Islak-Kuru El     229.000  20999.00
4   Songmics Yarış Koltuğu, Ofis Koltuğu, Oy       5.228   3199.99
..                                       ...         ...       ...
72        Karcher SC 2 Deluxe Buharlı Makine     148.000    159.00
73                  4'lü Çekmece Düzenleyici     267.000    389.98
74  Elektrikli motor turbo zemin fırçası baş       1.099   2740.00
75  Bacak Yastık. Viskoelastik Yastık. Ortop       8.626    460.00
76  Philips Hue GO V2 Taşınabilir Akıllı Led     122.000     69.00

[77 rows x 3 columns]

In [89]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output= False)
encoded_x = encoder.fit_transform(x)

In [91]:
encoded_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [97]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(encoded_x[:, [1, 2]])

array([[-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787, -0.11470787],
       [-0.11470787,

In [99]:
encoded_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [113]:
from sklearn.cluster import KMeans
kmeans = KMeans( n_clusters = 3 , random_state = 7 )
kmeans.fit(encoded_x)

KMeans(n_clusters=3, random_state=7)

In [129]:
pred_result = pd.DataFrame(kmeans.predict( encoded_x),columns = ['Clusters'])
pred_result

Clusters
0          1
1          1
2          1
3          1
4          1
..       ...
72         1
73         1
74         1
75         2
76         1

[77 rows x 1 columns]

In [137]:
from sklearn.metrics import silhouette_score, davies_bouldin_score
silhouettescore = silhouette_score(encoded_x , pred_result['Clusters'])
print("Silhouette Score:",silhouettescore )

Silhouette Score: 0.0005152781160328918


In [139]:
daviesbouldin = davies_bouldin_score(encoded_x, pred_result['Clusters'])
print("Davies-Bouldin Index:", daviesbouldin)

Davies-Bouldin Index: 0.9858160175773151
